name: docker-build-and-push

on:
  push:
    branches:
      - main
    tags:
  workflow_dispatch:

jobs:
  load-env:
    uses: ./.github/workflows/load-env.yaml

  docker-build:
    needs: load-env
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        name:
          - amd64-no-cuda
          - amd64-cuda
          - arm64-no-cuda
          - arm64-cuda
        include:
          - name: amd64-no-cuda
            cuda: no-cuda
            platform: amd64
            base_image_env: base_image
            lib_dir: x86_64
            setup-args: --no-nvidia
            additional-tag-suffix: ""
          - name: amd64-cuda
            cuda: cuda
            platform: amd64
            base_image_env: base_image
            lib_dir: x86_64
            additional-tag-suffix: -cuda
          - name: arm64-no-cuda
            cuda: no-cuda
            platform: arm64
            base_image_env: base_image
            lib_dir: aarch64
            setup-args: --no-nvidia
            additional-tag-suffix: ""
          - name: arm64-cuda
            cuda: cuda
            platform: arm64
            base_image_env: base_image
            lib_dir: aarch64
            additional-tag-suffix: -cuda
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set git config
        uses: autowarefoundation/autoware-github-actions/set-git-config@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Free disk space
        uses: ./.github/actions/free-disk-space

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            *.env
            *.repos
            .github/actions/docker-build-and-push/action.yaml
            .github/workflows/docker-build-and-push*.yaml
            ansible-galaxy-requirements.yaml
            ansible/**
            docker/**

      - name: Build 'Autoware'
        if: ${{ steps.changed-files.outputs.any_changed == 'true' ||
          github.event_name == 'workflow_dispatch' ||
          (github.event_name == 'push' && github.ref_type == 'tag') }}
        uses: ./.github/actions/docker-build-with-cross-compilation
        with:
          name: ${{ matrix.name }}
          platform: ${{ matrix.platform }}
          bake-target: autoware
          build-args: |
            *.platform=linux/${{ matrix.platform }}
            *.args.ROS_DISTRO=${{ needs.load-env.outputs.rosdistro }}
            *.args.BASE_IMAGE=${{ needs.load-env.outputs[format('{0}', matrix.base_image_env)] }}
            *.args.SETUP_ARGS=${{ matrix.setup-args }}
            *.args.LIB_DIR=${{ matrix.lib_dir }}
            *.cache-from=type=inline,ref=ghcr.io/${{ github.repository }}-buildcache:${{ matrix.cuda }}-${{ matrix.platform }}-${{ github.ref_name }}
            *.cache-from=type=inline,ref=ghcr.io/${{ github.repository }}-buildcache:${{ matrix.cuda }}-${{ matrix.platform }}-main
            *.cache-to=type=inline,ref=ghcr.io/${{ github.repository }}-buildcache:${{ matrix.cuda }}-${{ matrix.platform }}-${{ github.ref_name }},mode=max
            *.output=type=image,push=false
          tag-suffix: ${{ matrix.additional-tag-suffix }}-${{ matrix.platform }}
          tag-prefix: ${{ needs.load-env.outputs.rosdistro }}

      - name: Show disk space
        run: |
          df -h

  combine-and-push-multi-arch:
    needs: docker-build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Combine and push multi-arch images
        run: |
          for variant in "no-cuda" "cuda"; do
            docker buildx imagetools create -t ghcr.io/${{ github.repository }}:${{ needs.load-env.outputs.rosdistro }}-${variant} \
              ghcr.io/${{ github.repository }}:${{ needs.load-env.outputs.rosdistro }}-${variant}-amd64 \
              ghcr.io/${{ github.repository }}:${{ needs.load-env.outputs.rosdistro }}-${variant}-arm64
          done

          # Push the combined images to the repository
          for variant in "no-cuda" "cuda"; do
            docker push ghcr.io/${{ github.repository }}:${{ needs.load-env.outputs.rosdistro }}-${variant}
          done

      - name: Show pushed images
        run: |
          docker buildx imagetools inspect ghcr.io/${{ github.repository }}:${{ needs.load-env.outputs.rosdistro }}-no-cuda
          docker buildx imagetools inspect ghcr.io/${{ github.repository }}:${{ needs.load-env.outputs.rosdistro }}-cuda
